import os.path
import sys
import warnings

from mettoolbox import disaggregate, indices, pet, ret
from mettoolbox.toolbox_utils.src.toolbox_utils import tsutils

warnings.filterwarnings("ignore")


def main():
    from cltoolbox import Program
    from cltoolbox.rst_text_formatter import RSTHelpFormatter

    program = Program("mettoolbox", "0.0")

    program.add_subprog("disaggregate")
    program.add_subprog("pet")
    program.add_subprog("ret")
    program.add_subprog("indices")

    @program.command()
    def about():
        """Display version number and system information."""
        tsutils.about(__name__)

    @program.disaggregate.command("evaporation", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.evaporation)
    def evaporation_cli(
        method,
        source_units,
        input_ts="-",
        columns=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        lat=None,
    ):
        """Disaggregate daily to hourly data."""
        tsutils.printiso(
            disaggregate.evaporation(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                lat=lat,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command("humidity", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.humidity)
    def humidity_cli(
        method,
        source_units,
        input_ts="-",
        columns=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        precip_col=None,
        temp_min_col=None,
        temp_max_col=None,
        hum_min_col=None,
        hum_max_col=None,
        hum_mean_col=None,
        a0=None,
        a1=None,
        kr=None,
        hourly_temp=None,
        hourly_precip_hum=None,
        preserve_daily_mean=None,
    ):
        """Disaggregate daily humidity to hourly humidity data."""
        tsutils.printiso(
            disaggregate.humidity(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                precip_col=precip_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                hum_min_col=hum_min_col,
                hum_max_col=hum_max_col,
                hum_mean_col=hum_mean_col,
                a0=a0,
                a1=a1,
                kr=kr,
                hourly_precip_hum=hourly_precip_hum,
                hourly_temp=hourly_temp,
                preserve_daily_mean=preserve_daily_mean,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command(
        "dewpoint_temperature", formatter_class=RSTHelpFormatter
    )
    @tsutils.copy_doc(disaggregate.dewpoint_temperature)
    def dewpoint_temperature_cli(
        method,
        source_units,
        input_ts="-",
        columns=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        precip_col=None,
        temp_min_col=None,
        temp_max_col=None,
        hum_min_col=None,
        hum_max_col=None,
        hum_mean_col=None,
        a0=None,
        a1=None,
        kr=None,
        hourly_temp=None,
        hourly_precip_hum=None,
        preserve_daily_mean=None,
    ):
        """Disaggregate daily humidity to hourly humidity data."""
        tsutils.printiso(
            disaggregate.dewpoint_temperature(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                precip_col=precip_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                hum_min_col=hum_min_col,
                hum_max_col=hum_max_col,
                hum_mean_col=hum_mean_col,
                a0=a0,
                a1=a1,
                kr=kr,
                hourly_precip_hum=hourly_precip_hum,
                hourly_temp=hourly_temp,
                preserve_daily_mean=preserve_daily_mean,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command("precipitation", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.precipitation)
    def precipitation_cli(
        method,
        source_units,
        input_ts="-",
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        columns=None,
        masterstation_hour_col=None,
    ):
        """Disaggregate daily to hourly data."""
        tsutils.printiso(
            disaggregate.precipitation(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                masterstation_hour_col=masterstation_hour_col,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command("radiation", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.radiation)
    def radiation_cli(
        method,
        source_units,
        input_ts="-",
        columns=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        pot_rad=None,
        angstr_a=None,
        angstr_b=None,
        bristcamp_a=None,
        bristcamp_c=None,
        mean_course=None,
        lat=None,
        lon=None,
        hourly_rad=None,
        glob_swr_col=None,
        ssd_col=None,
        temp_min_col=None,
        temp_max_col=None,
    ):
        """Disaggregate daily to hourly data."""
        tsutils.printiso(
            disaggregate.radiation(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                pot_rad=pot_rad,
                angstr_a=angstr_a,
                angstr_b=angstr_b,
                bristcamp_a=bristcamp_a,
                bristcamp_c=bristcamp_c,
                hourly_rad=hourly_rad,
                lat=lat,
                lon=lon,
                glob_swr_col=glob_swr_col,
                ssd_col=ssd_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command("temperature", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.temperature)
    def temperature_cli(
        method,
        source_units,
        min_max_time="fix",
        mod_nighttime=False,
        input_ts="-",
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        temp_min_col=None,
        temp_max_col=None,
        temp_mean_col=None,
        lat=None,
        lon=None,
        hourly=None,
        max_delta=False,
    ):
        """Disaggregate daily temperature to hourly temperature."""
        tsutils.printiso(
            disaggregate.temperature(
                method,
                source_units,
                input_ts=input_ts,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
                min_max_time=min_max_time,
                mod_nighttime=mod_nighttime,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                temp_mean_col=temp_mean_col,
                lat=lat,
                lon=lon,
                hourly=hourly,
                max_delta=max_delta,
            ),
            tablefmt=tablefmt,
        )

    @program.disaggregate.command("wind_speed", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(disaggregate.wind_speed)
    def wind_speed_cli(
        method,
        source_units,
        input_ts="-",
        columns=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
        a=None,
        b=None,
        t_shift=None,
    ):
        """Disaggregate daily to hourly data."""
        tsutils.printiso(
            disaggregate.wind_speed(
                method,
                input_ts=input_ts,
                columns=columns,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                source_units=source_units,
                target_units=target_units,
                print_input=print_input,
                a=a,
                b=b,
                t_shift=t_shift,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("allen", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.allen)
    def allen_cli(
        lat,
        temp_min_col,
        temp_max_col,
        source_units,
        temp_mean_col=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            pet.allen(
                lat,
                temp_min_col,
                temp_max_col,
                source_units,
                temp_mean_col=temp_mean_col,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("blaney_criddle", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.blaney_criddle)
    def blaney_criddle_cli(
        bright_hours_col,
        source_units,
        temp_mean_col=None,
        temp_min_col=None,
        temp_max_col=None,
        k=0.85,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        names=None,
        target_units="mm",
        print_input=False,
        tablefmt="csv",
    ):
        """Evaporation calculated according to (Blaney, 1952)."""
        tsutils.printiso(
            pet.blaney_criddle(
                bright_hours_col=bright_hours_col,
                source_units=source_units,
                temp_mean_col=temp_mean_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                k=k,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("hamon", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.hamon)
    def hamon_cli(
        lat,
        source_units,
        temp_mean_col=None,
        temp_min_col=None,
        temp_max_col=None,
        k=1.2,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        """Evaporation calculated according to (Hamon, 1961)."""
        tsutils.printiso(
            pet.hamon(
                lat,
                source_units,
                temp_mean_col=temp_mean_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                k=k,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("hargreaves", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.hargreaves)
    def hargreaves_cli(
        lat,
        temp_min_col,
        temp_max_col,
        source_units,
        temp_mean_col=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            pet.hargreaves(
                lat,
                temp_min_col,
                temp_max_col,
                source_units,
                temp_mean_col=temp_mean_col,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("linacre", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.linacre)
    def linacre_cli(
        lat,
        elevation,
        source_units,
        temp_mean_col=None,
        temp_min_col=None,
        temp_max_col=None,
        tdew_col=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        """Evaporation calculated according to (Linacre, 1977)."""
        tsutils.printiso(
            pet.linacre(
                lat,
                elevation,
                source_units=source_units,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                temp_mean_col=temp_mean_col,
                tdew_col=tdew_col,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("oudin_form", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.oudin_form)
    def oudin_form_cli(
        lat,
        temp_min_col,
        temp_max_col,
        temp_mean_col=None,
        k1=100,
        k2=5,
        source_units=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            pet.oudin_form(
                lat,
                source_units=source_units,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                temp_mean_col=temp_mean_col,
                k1=k1,
                k2=k2,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("priestley_taylor", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.priestley_taylor)
    def priestley_taylor_cli(
        input_ts,
        lat,
        lon,
        temp_min_col,
        temp_max_col,
        srad_col,
        dayl_col,
        source_units,
        rh_col=None,
        u2_col=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            pet.priestley_taylor(
                lat,
                lon,
                temp_min_col,
                temp_max_col,
                srad_col,
                dayl_col,
                source_units,
                rh_col=rh_col,
                u2_col=u2_col,
                input_ts=input_ts,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.pet.command("romanenko", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(pet.romanenko)
    def romanenko_cli(
        source_units,
        temp_mean_col=None,
        temp_min_col=None,
        temp_max_col=None,
        rh_col=None,
        k=4.5,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        """Evaporation calculated according to (Romanenko, 1961)."""
        tsutils.printiso(
            pet.romanenko(
                source_units,
                temp_mean_col=temp_mean_col,
                temp_min_col=temp_min_col,
                temp_max_col=temp_max_col,
                rh_col=rh_col,
                k=k,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                names=names,
                target_units=target_units,
                print_input=print_input,
                tablefmt=tablefmt,
            )
        )

    @program.ret.command("penman_monteith", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(ret.penman_monteith)
    def penman_monteith_cli(
        input_ts,
        lat,
        lon,
        temp_min_col,
        temp_max_col,
        srad_col,
        dayl_col,
        source_units,
        rh_col=None,
        u2_col=None,
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        target_units=None,
        print_input=False,
        tablefmt="csv",
    ):
        """reference penman-monteith"""
        tsutils.printiso(
            ret.penman_monteith(
                lat,
                lon,
                temp_min_col,
                temp_max_col,
                srad_col,
                dayl_col,
                source_units,
                rh_col=rh_col,
                u2_col=u2_col,
                input_ts=input_ts,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.indices.command("spei", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(indices.spei)
    def spei_cli(
        rainfall,
        pet,
        source_units,
        nsmallest=None,
        nlargest=None,
        groupby="M",
        fit_type="lmom",
        dist_type="gam",
        scale=1,
        input_ts="-",
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        skiprows=None,
        index_type="datetime",
        names=None,
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            indices.spei(
                rainfall,
                pet,
                source_units,
                nsmallest=nsmallest,
                nlargest=nlargest,
                groupby=groupby,
                fit_type=fit_type,
                dist_type=dist_type,
                scale=scale,
                input_ts=input_ts,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                skiprows=skiprows,
                index_type=index_type,
                names=names,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    @program.indices.command("pe", formatter_class=RSTHelpFormatter)
    @tsutils.copy_doc(indices.pe)
    def pe_cli(
        rainfall,
        pet,
        source_units,
        nsmallest=None,
        nlargest=None,
        groupby="M",
        window=30,
        min_periods=None,
        center=False,
        win_type=None,
        closed=None,
        input_ts="-",
        start_date=None,
        end_date=None,
        dropna="no",
        clean=False,
        round_index=None,
        index_type="datetime",
        names=None,
        target_units="mm",
        print_input=False,
        tablefmt="csv",
    ):
        tsutils.printiso(
            indices.pe(
                rainfall,
                pet,
                source_units,
                nsmallest=nsmallest,
                nlargest=nlargest,
                groupby=groupby,
                window=window,
                min_periods=min_periods,
                center=center,
                win_type=win_type,
                closed=closed,
                input_ts=input_ts,
                start_date=start_date,
                end_date=end_date,
                dropna=dropna,
                clean=clean,
                round_index=round_index,
                names=names,
                target_units=target_units,
                print_input=print_input,
            ),
            tablefmt=tablefmt,
        )

    """Main"""
    if not os.path.exists("debug_mettoolbox"):
        sys.tracebacklimit = 0
    program()


if __name__ == "__main__":
    main()
